//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANNEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bai_viet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bai_viet()
        {
            this.Binh_luan = new HashSet<Binh_luan>();
        }
    
        public int BaiVietID { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> DanhMucID { get; set; }
        public string Hinh_Anh { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Danh_Muc Danh_Muc { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Binh_luan> Binh_luan { get; set; }
    }
}
