//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANNEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Binh_luan
    {
        public int BinhLuanID { get; set; }
        public string NoiDung { get; set; }
        public int BaiVietID { get; set; }
        public int UserID { get; set; }
    
        public virtual Bai_viet Bai_viet { get; set; }
        public virtual User User { get; set; }
    }
}
